// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFeRtHpj61Bs6q1icJeaU3K1Qje0NUBc4',
    appId: '1:550775581434:web:d8a464232cbabaafe7b743',
    messagingSenderId: '550775581434',
    projectId: 'sabak33-firebase1',
    authDomain: 'sabak33-firebase1.firebaseapp.com',
    storageBucket: 'sabak33-firebase1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD9dilsFkoxlHfd1Vyz8aDM096-7LilQc',
    appId: '1:550775581434:android:5c12e851df6573ede7b743',
    messagingSenderId: '550775581434',
    projectId: 'sabak33-firebase1',
    storageBucket: 'sabak33-firebase1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6D5gqCB3FUG_jyPA651_T29ptzC_u9lY',
    appId: '1:550775581434:ios:691f161e638ceafbe7b743',
    messagingSenderId: '550775581434',
    projectId: 'sabak33-firebase1',
    storageBucket: 'sabak33-firebase1.appspot.com',
    iosClientId: '550775581434-ubqogk96m2to5fa4ko394r93dueauhot.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabak33Firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6D5gqCB3FUG_jyPA651_T29ptzC_u9lY',
    appId: '1:550775581434:ios:73321d6835754755e7b743',
    messagingSenderId: '550775581434',
    projectId: 'sabak33-firebase1',
    storageBucket: 'sabak33-firebase1.appspot.com',
    iosClientId: '550775581434-m7742tnlpctunnds6nu1hlb1hvi37q2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabak33Firebase1.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFeRtHpj61Bs6q1icJeaU3K1Qje0NUBc4',
    appId: '1:550775581434:web:1635deb1713fa87de7b743',
    messagingSenderId: '550775581434',
    projectId: 'sabak33-firebase1',
    authDomain: 'sabak33-firebase1.firebaseapp.com',
    storageBucket: 'sabak33-firebase1.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBFeRtHpj61Bs6q1icJeaU3K1Qje0NUBc4',
    appId: '1:550775581434:web:0af7814c81703aabe7b743',
    messagingSenderId: '550775581434',
    projectId: 'sabak33-firebase1',
    authDomain: 'sabak33-firebase1.firebaseapp.com',
    storageBucket: 'sabak33-firebase1.appspot.com',
  );
}
